builds:
  -
    id: pretty-json
    env:
      - CGO_ENABLED=0
    main: main.go
    binary: pretty-json
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "cj_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: zip
    format_overrides:
      - goos: linux
        format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'