name: release pretty-json
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: prepare modules
        run: make prepare
        env:
          GOPATH: ${{ github.workspace }}/gopath

      - name: release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPATH: ${{ github.workspace }}/gopath
